name: groovin_widgets
description: A Flutter widget library containing custom widgets created and edited by GroovinChip.
version: 2.0.0-nullsafety.0
homepage: https://github.com/GroovinChip/GroovinWidgets
#---
# Publishing steps:
# 1) pana --no-warning
# 2) flutter packages pub publish --dry-run
# 3) flutter packages pub publish
#---

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
